{{- range .Values.users }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ include "lib.fullname" $ }}-{{ .name }}
  labels:
    {{- include "lib.labels" $ | nindent 4 }}
  annotations:
    {{- include "lib.argocdAnnotations" $ | nindent 4 }}
spec:
  deletionPolicy: None
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: {{ include "lib.fullname" $ }}-pguser-{{ .name }}
  data:
    - match:
        remoteRef:
          remoteKey: tenant/{{ $.Values.tenant }}/postgres/{{ $.Values.name }}/{{ .name }}
{{- end }}
