apiVersion: v1
kind: Namespace
metadata:
  name: managed-services
  labels:
    egress: internet
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: managed-services
  namespace: managed-services
spec:
  interval: 10m
  ref:
    branch: main
  timeout: 1m
  url: https://github.com/thecodingsheikh/managed-services