apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: tenant
spec:
  schema:
    apiVersion: v1alpha1
    group: managedservices.thecodingsheikh.io
    kind: Tenant
    spec:
      values: object
  resources:
    - id: release
      readyWhen:
        - ${release.status.conditions[?type == "Ready"].status == "True"}
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2beta2
        kind: HelmRelease
        metadata:
          name: ${schema.spec.values.name}
          namespace: flux
        spec:
          releaseName: ${schema.spec.values.name}
          targetNamespace: flux
          chart:
            spec:
              reconcileStrategy: Revision
              chart: charts/tenant
              sourceRef:
                kind: GitRepository
                name: managed-services
                namespace: flux
              interval: 5m
          interval: 15m
          values: ${schema.spec.values}
          install:
            remediation:
              retries: 3
          upgrade:
            remediation:
              retries: 3
              remediateLastFailure: true
          timeout: 5m