apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: tenant
spec:
  schema:
    apiVersion: v1alpha1
    group: managedservices.thecodingsheikh.io
    kind: Tenant
    spec:
      values: object
  resources:
    - id: release
      readyWhen:
        - ${release.status.conditions.exists(c, c.type == 'Ready' && c.status == 'True')}
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2beta2
        kind: HelmRelease
        metadata:
          name: ${schema.spec.values.name}-${schema.kind.lower()}
          namespace: ${schema.metadata.namespace}
          ownerReferences:
            - apiVersion: ${schema.apiVersion}
              kind: ${schema.kind}
              name: ${schema.metadata.name}
              uid: ${schema.metadata.uid}
              blockOwnerDeletion: true
              controller: false
          annotations:
            argocd.argoproj.io/tracking-id: ${schema.metadata.?annotations["argocd.argoproj.io/tracking-id"]}
        spec:
          releaseName: ${schema.spec.values.name}-${schema.kind.lower()}
          targetNamespace: ${schema.metadata.namespace}
          chart:
            spec:
              reconcileStrategy: Revision
              chart: charts/${schema.kind.lower()}
              sourceRef:
                kind: GitRepository
                name: managed-services
                namespace: managed-services
              interval: 5m
          interval: 15m
          values: ${schema.spec.values}
          install:
            remediation:
              retries: 3
          upgrade:
            remediation:
              retries: 3
              remediateLastFailure: true
          timeout: 5m