apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: &name postgres
  title: Managed Postgres Instance
  description: Create a managed Postgres instance
  tags:
    - *name
    - kubernetes
    - managed-service
spec:
  owner: platform-team
  type: service

  # Parameters reference charts/<service>/values.schema.json structure
  parameters:
    ##### Keep this step as is #####
    - $yaml: https://github.com/thecodingsheikh/managed-services/blob/main/software-templates/shared/parameters/tenant-selector.yaml
    ################################
    - title: Postgres Configuration
      required:
        - name
      properties:
        serviceType:
          type: string
          # Must be same as template name
          default: *name
          # Must be hidden
          ui:widget: hidden
        name:
          title: Postgres Instance Name
          type: string
          description: Unique name of the postgres instance (lowercase, alphanumeric with dashes)
          pattern: "^[a-z][a-z0-9-]*$"
          minLength: 1
          maxLength: 63
          ui:autofocus: true
        nameValidator:
          type: string
          ui:field: ScaffolderFieldValidator
          ui:options:
            watchField: name
            validationType: api
            apiPath: proxy/k8s/managedservices.thecodingsheikh.io/v1alpha1/postgreses
            jmesPath: "items[?metadata.name == '{{ value }}']"
            errorMessage: "Postgres '{{ value }}' is already in use"
    - title: Instance Configuration
      required:
        - instanceType
        - storage
      properties:
        instanceType:
          title: Instance Type
          type: string
          description: The database instance type (RDS-like sizing)
          default: db.t3.micro
          enum:
            - db.t3.micro
            - db.t3.small
            - db.t3.medium
            - db.m5.large
        
        storage:
          title: Storage Configuration
          type: object
          properties:
            size:
              title: Storage Size
              type: string
              description: The size of the storage volume
              default: 10Gi
              pattern: '^\d+(Gi|Mi)$'

        postgresVersion:
          title: Postgres Version
          type: integer
          description: Major version of Postgres
          default: 16
          enum:
            - 13
            - 14
            - 15
            - 16

        ha:
          title: High Availability
          type: object
          properties:
            enabled:
              title: Enable HA
              type: boolean
              description: Enable High Availability (multi-replica)
              default: false
            replicas:
              title: Replicas
              type: integer
              description: Number of replicas (ignored if disabled)
              default: 3
              minimum: 2

        backup:
          title: Backup Configuration
          type: object
          properties:
            enabled:
              title: Enable Backups
              type: boolean
              description: Enable automated backups
              default: true
            schedule:
              title: Schedule
              type: string
              description: Cron schedule
              default: "0 1 * * *"
            retain:
              title: Retention
              type: integer
              description: Number of backups to keep
              default: 7

  steps:
    - $yaml: https://github.com/thecodingsheikh/managed-services/blob/main/software-templates/shared/steps/fetch-template.yaml
    - $yaml: https://github.com/thecodingsheikh/managed-services/blob/main/software-templates/shared/steps/push-manifest.yaml

  output:
    text:
      - title: Postgres Database Created
        content: |
          Your Postgres database is being created. You can view it in the catalog once it is ready.
