apiVersion: managedservices.thecodingsheikh.io/v1alpha1
kind: ${{ values.params.serviceType | replace("-", " ") | title | replace(" ", "")}}
metadata:
  name: "${{ parameters.tenant }}-tenant{% if parameters.serviceType != 'tenant' %}-${{ parameters.name }}-${{ parameters.serviceType }}{% endif %}"
  annotations:
    lab.backstage.io/add-to-catalog: "true"
    lab.backstage.io/system-type: app
    lab.backstage.io/component-type: service
    lab.backstage.io/lifecycle: managed
    lab.backstage.io/links: string
    {% if parameters.serviceType != 'tenant' %}
    lab.backstage.io/dependsOn: component:default/${{ parameters.tenant }}-tenant
    {% endif %}
    lab.backstage.io/title: ${{ parameters.tenant | replace("-", " ") | title }} Tenant {% if parameters.serviceType != 'tenant' %} ${{ parameters.name | replace("-", " ") | title }} ${{ parameters.serviceType | replace("-", " ") | title }}{% endif %}
    lab.backstage.io/name: ${{ parameters.tenant }}-tenant{% if parameters.serviceType != 'tenant' %}-${{ parameters.name }}-${{ parameters.serviceType }}{% endif %}
    lab.backstage.io/system: ${{ values.params.serviceType }}
    managedservices.thecodingsheikh.io/type: ${{ values.params.serviceType }}

spec:
  values:
