apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: tenant
  title: Managed Tenant
  description: Create a tenant
  tags:
    - kubernetes
    - managed-service
spec:
  owner: platform-team
  type: resource

  # Parameters reference charts/tenant/values.schema.json structure
  parameters:
    - title: Tenant Configuration
      required:
        - name
        - owners
      properties:
        serviceType:
          type: string
          default: tenant
          # Must be hidden
          ui:widget: hidden
        name:
          title: Tenant Name
          type: string
          description: Unique name for the tenant (lowercase, alphanumeric with dashes)
          pattern: "^[a-z][a-z0-9-]*$"
          minLength: 1
          maxLength: 63
          ui:autofocus: true
        nameValidator:
          type: string
          ui:field: ScaffolderFieldValidator
          ui:options:
            watchField: name
            validationType: api
            apiPath: proxy/k8s/managedservices.thecodingsheikh.io/v1alpha1/namespaces/managed-services/tenants
            jmesPath: "items[?metadata.name == '{{ value }}']"
            errorMessage: "Tenant '{{ value }}' is already in use"
        owners:
          title: Tenant Owners
          type: array
          description: List of tenant owners (Can be changed later)
          minItems: 1
          ui:options:
            orderable: true
          items:
            type: object
            required:
              - subject
              - role
            properties:
              subject:
                title: Subject
                type: string
                description: Name of the user or group
                ui:field: OwnerPicker
                ui:options:
                  catalogFilter:
                    kind: [Group, User]
              role:
                title: Role
                type: string
                description: Role to assign
                default: view
                enum:
                  - admin
                  - edit
                  - view
                enumNames:
                  - Admin
                  - Edit
                  - View

  steps:
    - $yaml: https://github.com/thecodingsheikh/managed-services/blob/main/software-templates/shared/steps/fetch-template.yaml
    - $yaml: https://github.com/thecodingsheikh/managed-services/blob/main/software-templates/shared/steps/catalog-register.yaml
    - $yaml: https://github.com/thecodingsheikh/managed-services/blob/main/software-templates/shared/steps/push-tenant-manifest.yaml

  output:
    links:
      - title: View in Catalog
        icon: catalog
        url: ${{ steps['register-catalog'].output.catalogInfoUrl }}
    text:
      - title: Tenant Created
        content: |
          Your tenant **${{ parameters.name }}** has been created successfully