apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: tenant
  title: Managed Tenant
  description: Create a managed tenant
  tags:
    - tenant
    - kubernetes
    - managed-service
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Tenant Configuration
      required:
        - tenant
      properties:
        tenant:
          title: Tenant Name
          type: string
          description: Unique name for the tenant (lowercase, alphanumeric with dashes)
          pattern: "^[a-z][a-z0-9-]*$"
          minLength: 1
          maxLength: 63
          ui:autofocus: true
        tenantValidator:
          type: string
          ui:field: ScaffolderFieldValidator
          ui:options:
            watchField: tenant
            validationType: api
            apiPath: proxy/k8s/managedservices.thecodingsheikh.io/v1alpha1/tenants
            jmesPath: "items[?metadata.name == '{{ value }}']"
            errorMessage: "Tenant '{{ value }}' is already in use"
    - title: Owners
      required:
        - owners
      properties:
        owners:
          title: Tenant Owners
          type: array
          description: List of tenant owners
          minItems: 1
          ui:options:
            orderable: true
          items:
            type: object
            required:
              - subject
              - role
            properties:
              subject:
                title: Subject
                type: string
                description: Name of the user or group
                ui:field: OwnerPicker
                ui:options:
                  catalogFilter:
                    kind: [Group, User]
              role:
                title: Role
                type: string
                description: Role to assign
                default: view
                enum:
                  - admin
                  - edit
                  - view
                enumNames:
                  - Admin
                  - Edit
                  - View

  steps:
    - id: fetch-skeleton
      name: Scaffold Manifest
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./output
        values:
          params: ${{ parameters }}
    - id: push-manifest
      name: Push Manifest
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=thecodingsheikh&repo=managed-services-releases
        branchName: "create-${{ parameters.tenant }}-tenant"
        sourcePath: ./output
        targetPath: "${{ parameters.tenant }}/manifest.yaml"
        title: "create ${{ parameters.tenant }} tenant"
        description: "create ${{ parameters.tenant }} tenant"
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: backstage@thecodingsheikh.io

  output:
    text:
      - title: Tenant Created
        content: |
          Your tenant is being created.