apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.params.name }}-tenant
  description: Managed Tenant - ${{ values.params.name }}
  title: ${{ values.params.name | replace("-", " ") | title }} Tenant
  tags:
    - tenant
    - managed-service
spec:
  type: managed-service
  owner: platform-team
  system: tenant