apiVersion: managedservices.thecodingsheikh.io/v1alpha1
kind: Tenant
metadata:
  name: ${{ values.params.name }}-${{ values.params.serviceType }}
  annotations:
    lab.backstage.io/add-to-catalog: "true"
    lab.backstage.io/system-type: app
    lab.backstage.io/component-type: service
    lab.backstage.io/lifecycle: managed
    lab.backstage.io/links: string
    managedservices.thecodingsheikh.io/type: ${{ values.params.serviceType }}
    lab.backstage.io/title: ${{ values.params.name | replace("-", " ") | title }} ${{ values.params.serviceType | replace("-", " ") | title }}
    lab.backstage.io/name: ${{ values.params.name }}-${{ values.params.serviceType }}
    lab.backstage.io/owner: ${{ values.params.owners[0].subject }}
    lab.backstage.io/system: ${{ values.params.serviceType }}

spec:
  values:
    name: ${{ values.params.name }}
    owners:
      {%- for owner in values.params.owners %}
      - subject: ${{ owner.subject | dump }}
        role: ${{ owner.role }}
      {%- endfor %}
