apiVersion: managedservices.thecodingsheikh.io/v1alpha1
# ┌──────────────────────────────────────────────────────────────────┐
# │ TENANT SKELETON — This is the root service skeleton.            │
# │ Non-tenant services are generated via `make scaffold`.          │
# └──────────────────────────────────────────────────────────────────┘
kind: Tenant
metadata:
  name: "${{ values.params.tenant }}-tenant"
  annotations:
    # Backstage catalog discovery through kerasky kubernetes ingestor plugin
    lab.backstage.io/add-to-catalog: "true"
    lab.backstage.io/system-type: app
    lab.backstage.io/component-type: service
    lab.backstage.io/lifecycle: managed
    lab.backstage.io/title: ${{ values.params.tenant | replace("-", " ") | title }} Tenant
    lab.backstage.io/name: ${{ values.params.tenant }}-tenant
    lab.backstage.io/system: tenant
    # Backstage entity scaffolder plugin
    backstage.io/last-applied-configuration: '${{ values.params | dump }}'
    backstage.io/scaffolder-template: template:default/tenant
    backstage.io/immutable-fields: 'tenant'
spec:
  values:
    tenant: ${{ values.params.tenant }}
    owners:
      {%- for owner in values.params.owners %}
      - subject: ${{ owner.subject }}
        role: ${{ owner.role }}
      {%- endfor %}
