apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: managed-services
  description: Collection of all the managed services software templates
spec:
  targets:
    - ./tenant/template.yaml
