apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lib.fullname" . }}
  labels:
    {{- include "lib.labels" . | nindent 4 }}
  annotations:
    {{- include "lib.argocdAnnotations" . | nindent 4 }}
