apiVersion: v1
kind: Service
metadata:
  name: {{ include "lib.fullname" . }}
  labels:
    {{- include "lib.labels" . | nindent 4 }}
  annotations:
    {{- include "lib.argocdAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "lib.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
